// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrybryhPElk6lNQmOPvkjsztn3ZagQ5QE',
    appId: '1:1090452740865:web:540a548bf9096a80aa9900',
    messagingSenderId: '1090452740865',
    projectId: 'chat-app-flutter-e6de4',
    authDomain: 'chat-app-flutter-e6de4.firebaseapp.com',
    storageBucket: 'chat-app-flutter-e6de4.appspot.com',
    measurementId: 'G-0MBQR26XHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVkNsp0ACyQ8Gr_kS2jzZsdDfWHGLDCiY',
    appId: '1:1090452740865:android:c46c81d3a43468b8aa9900',
    messagingSenderId: '1090452740865',
    projectId: 'chat-app-flutter-e6de4',
    storageBucket: 'chat-app-flutter-e6de4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUi6JxTN1jt66HDeNcv7k3WvUMIdRBv3s',
    appId: '1:1090452740865:ios:292af26c3a25841daa9900',
    messagingSenderId: '1090452740865',
    projectId: 'chat-app-flutter-e6de4',
    storageBucket: 'chat-app-flutter-e6de4.appspot.com',
    iosClientId: '1090452740865-rsqoutjlftpocit013ergse0ntul0ce4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUi6JxTN1jt66HDeNcv7k3WvUMIdRBv3s',
    appId: '1:1090452740865:ios:1023fd6bbaf98830aa9900',
    messagingSenderId: '1090452740865',
    projectId: 'chat-app-flutter-e6de4',
    storageBucket: 'chat-app-flutter-e6de4.appspot.com',
    iosClientId: '1090452740865-1drpoqe5lqaduhk83ieojp30pm0t4aks.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
